modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="add_pattern_to_network_tool"
version="${version}"
displayName="Add Pattern to Network Tool"
authors="Madgique"
description='''Add Pattern to Network Tool - A clean mod template'''

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.add_pattern_to_network_tool]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.add_pattern_to_network_tool]]
    modId="architectury"
    mandatory=true
    versionRange="[9.2.14,)"
    ordering="NONE"
    side="BOTH"


